Repository detra-lab/tsc, pull requests merged in 2023-06, with the labels that each got.

#10 fix: move node types to dedicated configs
  .changeset/cool-lamps-develop.md
  base/tsconfig.json
  lit/tsconfig.json
  node/tsconfig.cjs.json
  node/tsconfig.esm.json
  react/tsconfig.json
Labels: scope :: enhancement 🚀, status :: needs review 🔎

#13 fix: remove the target from react and lit
  .changeset/small-rings-beg.md
  base/tsconfig.json
  node/tsconfig.cjs.json
  node/tsconfig.esm.json
Labels: scope :: chore ⚙️, status :: needs review 🔎

#15 chore: update dependencies
  .prettierignore
  package.json
  pnpm-lock.yaml
Labels: scope :: chore ⚙️

#16 chore: add changeset
  .changeset/rotten-pots-laugh.md
Labels: scope :: chore ⚙️

#19 chore: update github action workflows
  .changeset/config.json
  .changeset/tidy-snakes-itch.md
  .github/workflows/main.yaml
Labels: scope :: chore ⚙️

#22 chore: test the release process
  .changeset/soft-grapes-joke.md
  CHANGELOG.md
Labels: scope :: chore ⚙️
